# The Yokoyama Lab {#the-lab}

Yokoyama Lab Overview 

## Yokoyama Lab Mission {#lab-mission}



## Our Philosophy {#lab-philosophy}



## Our Research


## Our Core Values {#lab-values}

The way we conduct ourselves is a critical part of how we conduct science. Lab members will strive to uphold the following values:

* **Integrity**: Like many things in the world, science is built on trust and honesty. We will pursue rigorous and transparent research, ensuring our work is credible and reliable.

* **Humility**: By accepting that we may not decidedly know or understand everything, we are open to new perspectives. We are willing to admit we made mistakes and share what we have learned from them.

* **Kindness**: Science involves skepticism and criticism, but that does not mean it cannot be done with care and empathy. We hope to be respectful members of the scientific community, being considerate and supportive to our colleagues at all levels. 

* **Diversity**: Science should reflect the vast perspectives, experiences and people that exist in the world. Our lab hopes to be inclusive to all, and promote equity throughout science.

## Our Location





